{% set version = "24.3.0" %}

package:
  name: pyopenssl
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/p/pyOpenSSL/pyopenssl-{{ version }}.tar.gz
  sha256: 49f7a019577d834746bc55c5fce6ecbcec0f2b4ec5ce1cf43a9a173b8138bb36

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vvv

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools
  run:
    - python >=3.7
    - cryptography >=41.0.5,<44

test:
  source_files:
    - tests/*
  commands:
    - pytest tests
  requires:
    - pytest
    - pretend
    - pytest-rerunfailures
  imports:
    - OpenSSL
    - OpenSSL.crypto
    - OpenSSL.rand
    - OpenSSL.SSL

about:
  home: https://github.com/pyca/pyopenssl
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Python wrapper module around the OpenSSL library
  description: |
    pyOpenSSL is a high-level wrapper around a subset of the OpenSSL library.
    It includes:
    -SSL.Connection objects, wrapping the methods of Python's portable sockets
    -Callbacks written in Python
    -Extensive error-handling mechanism, mirroring OpenSSL's error codes
    and much more.
  doc_url: https://pyopenssl.readthedocs.org/en/stable/
  doc_source_url: https://github.com/pyca/pyopenssl/blob/master/doc/index.rst
  dev_url: https://github.com/pyca/pyopenssl

extra:
  recipe-maintainers:
    - goanpeca
    - nehaljwani
